### PR TITLE
Fix 'rtc_gpio_desc was not declared' compile error with arduino-esp32 v2.0.0

### LINKED ISSUE #100: ESP32 compile error with arduino-esp32 v2.0.0-rc1 (error: 'rtc_gpio_desc' was not declared in this scope)
### Description

The OneWire library (latest version 2.3.5) fails to compile with arduino-esp32 v2.0.0-rc1 due to undeclared symbol 'rtc_gpio_desc'. This symbol apparently does not exist anymore under arduino-esp32 v2.0.0-rc1, and has been renamed to rtc_io_desc.

### Steps To Reproduce Problem

1. Install Arduino IDE
2. Install ESP32 support for Arduino, 2.0.0-rc1 (required for ESP32-S2 and ESP32-C3 support)
3. Install this library and some library requiring it
4. Compile any sketch that pulls OneWire (no need to flash anything, as this is a compile issue)

### Hardware & Software

Board: ESP32 (YUBOX)
Arduino IDE version: 1.8.15
Teensyduino version (if using Teensy)
Version info & package name (from Tools > Boards > Board Manager): esp32 by Espressif systems v2.0.0-rc1
Operating system & version: Fedora 34 x86_64
Any other software or hardware?

### Arduino Sketch

```cpp
#include <Arduino.h>
// Pulling header file is enough to trigger the compile error
#include <OneWire.h>

void setup() {
// No code required to trigger error
}

void loop() {
// No code required to trigger error
}
```

### Errors or Incorrect Output
```
In file included from /home/alex/Arduino/libraries/OneWire/OneWire.cpp:144:
/home/alex/Arduino/libraries/OneWire/util/OneWire_direct_gpio.h: In function 'void directModeInput(uint32_t)':
/home/alex/Arduino/libraries/OneWire/util/OneWire_direct_gpio.h:161:26: error: 'rtc_gpio_desc' was not declared in this scope
         uint32_t rtc_reg(rtc_gpio_desc[pin].reg);
                          ^~~~~~~~~~~~~
/home/alex/Arduino/libraries/OneWire/util/OneWire_direct_gpio.h:161:26: note: suggested alternative: 'rtc_io_desc'
         uint32_t rtc_reg(rtc_gpio_desc[pin].reg);
                          ^~~~~~~~~~~~~
                          rtc_io_desc
/home/alex/Arduino/libraries/OneWire/util/OneWire_direct_gpio.h: In function 'void directModeOutput(uint32_t)':
/home/alex/Arduino/libraries/OneWire/util/OneWire_direct_gpio.h:189:26: error: 'rtc_gpio_desc' was not declared in this scope
         uint32_t rtc_reg(rtc_gpio_desc[pin].reg);
                          ^~~~~~~~~~~~~
/home/alex/Arduino/libraries/OneWire/util/OneWire_direct_gpio.h:189:26: note: suggested alternative: 'rtc_io_desc'
         uint32_t rtc_reg(rtc_gpio_desc[pin].reg);
                          ^~~~~~~~~~~~~
                          rtc_io_desc
```

### LINKED ISSUE #103: Getting Guru Meditation Error when using DallasTemperature && OneWire with Wifi.h on esp32
I'm getting this error, when trying to use Wifi + DallasTemperature && OneWire on my esp32. Temperature sensor is Gravity DS18B20.

 When I don't use Wifi it works fine.

This is an error code

```
09:41:17.049 -> Guru Meditation Error: Core  1 panic'ed (LoadProhibited). Exception was unhandled.
09:41:17.082 -> 
09:41:17.082 -> Core  1 register dump:
09:41:17.082 -> PC      : 0x400d3b40  PS      : 0x00060433  A0      : 0x800d4488  A1      : 0x3ffb2710  
09:41:17.082 -> A2      : 0x3f40af28  A3      : 0x0000001c  A4      : 0x0a4c4c55  A5      : 0x3ff49000  
09:41:17.082 -> A6      : 0x00000020  A7      : 0x00000000  A8      : 0x800d3b15  A9      : 0x3ffb26d0  
09:41:17.082 -> A10     : 0x00060420  A11     : 0x3ffc2cac  A12     : 0x3ffc2ca4  A13     : 0xb33fffff  
09:41:17.082 -> A14     : 0x00000001  A15     : 0x00000001  SAR     : 0x00000020  EXCCAUSE: 0x0000001c  
09:41:17.115 -> EXCVADDR: 0x0a4c4c55  LBEG    : 0x400df328  LEND    : 0x400df332  LCOUNT  : 0x00000000  
09:41:17.115 -> 
09:41:17.115 -> 
09:41:17.115 -> Backtrace:0x400d3b3d:0x3ffb27100x400d4485:0x3ffb2750 0x400d476c:0x3ffb2780 0x400d2782:0x3ffb27b0 0x400d53b7:0x3ffb2820 

```

Here I have it decoded

```
Decoding 5 results
0x400d3b3d: OneWire::reset() at /home/suomi/Arduino/libraries/OneWire/util/OneWire_direct_gpio.h line 165
:  (inlined by) OneWire::reset() at /home/suomi/Arduino/libraries/OneWire/OneWire.cpp line 172
0x400d4485: OneWire::search(unsigned char*, bool) at /home/suomi/Arduino/libraries/OneWire/OneWire.cpp line 388
0x400d476c: DallasTemperature::begin() at /home/suomi/Arduino/libraries/DallasTemperature/DallasTemperature.cpp line 113
0x400d2782: setup() at /home/suomi/Arduino/sketch_sep18a/sketch_sep18a.ino line 53
0x400d53b7: loopTask(void*) at /home/suomi/.arduino15/packages/esp32/hardware/esp32/2.0.0/cores/esp32/main.cpp line 38
```

also with backtracked lines in the files mentioned above

```
1. ESP_REG(rtc_reg) = ESP_REG(rtc_reg) & ~(rtc_io_desc[pin].mux);

2. DIRECT_MODE_INPUT(reg, mask);

3.if (!reset()) {

4.while (_wire->search(deviceAddress)) {

5.sensors.begin();

6.void loopTask(void *pvParameters)
{
    setup();

``` 

And my executed code

```
#include <OneWire.h>
#include <DallasTemperature.h>
#include <WiFi.h>


// Wifi Settings
#define WIFI_NETWORK "name"
#define WIFI_PASSWORD "pass"
#define WIFI_TIMOUT_MS 20000

const int oneWireBus = 32;
OneWire oneWire(oneWireBus);
DallasTemperature sensors(&oneWire);
int status;



int connectToWiFi() {
    Serial.println(" ");
    Serial.print("Connencting to WiFi");
    Serial.print(" ");
    WiFi.mode(WIFI_STA);
    WiFi.begin(WIFI_NETWORK, WIFI_PASSWORD);

    unsigned long startAttemptTime = millis();

    while(WiFi.status() != WL_CONNECTED && millis() - startAttemptTime < WIFI_TIMOUT_MS) {
        Serial.print(".");
        delay(700);
    }

    if (WiFi.status() != WL_CONNECTED) {
        Serial.println("Failed connect to WiFi!");
        return 0;

    }

    else {
        Serial.print("Connected to WiFi");
        Serial.println(WIFI_NETWORK);
        Serial.println(WiFi.localIP());
        return 1;
    }
}


void setup() {
    status = connectToWiFi();
    Serial.begin(115200);
    sensors.begin();


void loop() {
        
}
```

I'm not very good in c++, could someone please help me? `LoadProhibited`: It looks like it trying to access a memory that it shouldn't?

### PR DESCRIPTION
**Pull request by codepam**
When using arduino-esp32 v2.0.0, the call to rtc_gpio_desc is replaced by rtc_io_desc and the io number is assigned by rtc_io_number_get.

Fixes #100
Fixes #103

### CODE REVIEW

**Comment by codepam** [comment]
Fixes #103

**Comment by Michal-Szczepaniak** [comment]
+1 works perfectly on my esp32

**Comment by PaulStoffregen** [comment]
Thanks!

**Comment by damianjwilliams** [comment]
Not working on my ESP32-S2-WROVER. The error disappears and it compiles but the temperatures are wrong. 
```
18:52:03.339 -> -127.00ºC
18:52:03.339 -> -196.60ºF
```

**Comment by PaulStoffregen** [comment]
I'm waiting on more ESP32 user feedback before publishing a new OneWire version. So far only 3 people have reported results with #102 applied.

Michal-Szczepaniak said "+1 works perfectly on my esp32"
damianjwilliams said "Not working on my ESP32-S2-WROVER"
ClemensGruber said "I downgraded to Arduino ESP core 1.0.6 and code is still compiling and DS18B20 working as expected".

Now is the time to contribute by just installing the latest and running on your ESP32 hardware, then post clear feedback. Is this ready to publish as a new version to Arduino's library manager?

**Comment by Michal-Szczepaniak** [comment]
@damianjwilliams are you using parasitic power? I only have one thermometer, connected on 1m wire or just directly to the board (both wtih the 4.7k resistor), without parasitic power. Also i have esp-wroom-32. I can check it on esp32-s2 on top of saola r1

**Comment by damianjwilliams** [comment]
@Michal-Szczepaniak I'm using the regular 3.3 V output from the module. It all seems to work fine on my ESP-32-WROOM. Also @PaulStoffregen I wrote the wrong module, now edited to ESP-32-S2-WROOM. Thanks!

**Comment by Michal-Szczepaniak** [comment]
now we know that issue might be related to esp32-s2 :)

**Comment by codepam** [comment]
Sorry for not replying earlier, @damianjwilliams has the problem been solved? If an ESP32-S2 board is selected, the compiler seems to be entering both preprocessor checks, but I have no access to such a board so as to test the code.
What is so different with S2 boards?

**Comment by dukess** [comment]
@PaulStoffregen 
Hi! One more report about OneWire + ESP32 SDK 2.0.x:
I use Olimex ESP32-EVB board. When i tried to run current version MCU can't found sensors on bus.
When i use patch https://github.com/PaulStoffregen/OneWire/pull/93 , MCU found sensors without problem.
